name: Monthly Package Update Reminder
on:
  workflow_dispatch:
#   schedule:
#     - cron: "0 0 1 * *" # Runs at 00:00 UTC on the first day of every month

jobs:
  create_issue:
    name: Create package update reminder issue
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      issues: write
    steps:
      - name: Create package update reminder issue in selected repositories
        run: |
          new_issue_url=$(gh issue create \
            --repo "${{ env.GH_REPO }}" \
            --title "${{ env.TITLE }}" \
            --label "${{ env.LABELS }}" \
            --body "${{ env.BODY }}")
          echo "Issue created: $new_issue_url"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: "alstraab/alstra-web" ## Space-separated list of repositories
          TITLE: "Monthly Dependency Update Reminder"
          LABELS: "dependencies"
          BODY: |
            It's time to check and update our packages to the latest versions.
            - [ ] Review outdated packages
            - [ ] Update packages
            - [ ] Run tests
            - [ ] Merge updates after successful review and testing
