name: Monthly Package Update Reminder
on:
  workflow_dispatch:
#   schedule:
#     - cron: "0 0 1 * *" # Runs at 00:00 UTC on the first day of every month

jobs:
  create_issue:
    name: Create package update reminder issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create package update reminder issue in selected repositories
        run: |
          for REPO in $REPOS; do
            echo "Creating issue in $REPO"
            new_issue_url=$(gh issue create \
              --repo "$REPO" \
              --title "$TITLE" \
              --label "$LABELS" \
              --body "$BODY")
            echo "Issue created: $new_issue_url"
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOS: "alstraab/alstra-web" ## Space-separated list of repositories
          TITLE: "Monthly Dependency Update Reminder"
          LABELS: "dependencies"
          BODY: |
            It's time to check and update our packages to the latest versions.
            - [ ] Review outdated packages
            - [ ] Update packages
            - [ ] Run tests
            - [ ] Merge updates after successful review and testing
