name: Template Scheduled Update Reminder

on:
  workflow_call:
    inputs:
      REPO:
        description: "Repository name (format: org/repo)"
        required: true
        type: string

jobs:
  create_issue:
    name: Create package update reminder issue
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      issues: write
    steps:
      - name: Create package update reminder issue in selected repositories
        run: |
          new_issue_url=$(gh issue create \
            --repo "${{ env.GH_REPO }}" \
            --title "${{ env.TITLE }}" \
            --label "${{ env.LABELS }}" \
            --body "${{ env.BODY }}" \
            --assignee "${{ env.ASSIGNEES }}")
          echo "Issue created: $new_issue_url"
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_REPO: ${{ inputs.REPO }}
          TITLE: "Monthly Dependency Update Reminder"
          LABELS: "dependencies"
          ASSIGNEES: juliandreas,klastarnstrom,ajanryd,karl-m-t,Antonia-91
          BODY: |
            It's time to check and update our packages to the latest versions. Be careful with major updates (sometimes it's better to wait with them).
            - [ ] Review outdated packages
            - [ ] Update packages
            - [ ] Run tests
          PINNED: true
