name: Scheduled Update Reminder

on:
  schedule:
    - cron: "0 0 * * 1" # Runs at 00:00 UTC every Monday

jobs:
  check-first-monday:
    runs-on: ubuntu-latest
    outputs:
      is_first_monday: ${{ steps.check-date.outputs.is_first_monday }}
    steps:
      - name: Check if it's the first Monday of the month
        id: check-date
        run: |
          TODAY=$(date +'%d')
          if [ "$TODAY" -le "7" ]; then
              echo "It's the first Monday of the month."
              echo "::set-output name=is_first_monday::true"
          else
              echo "It's not the first Monday of the month."
              echo "::set-output name=is_first_monday::false"
          fi

  alstra-web:
    needs: check-first-monday
    if: needs.check-first-monday.outputs.is_first_monday == 'true'
    uses: ./.github/workflows/template-scheduled-reminder.yml
    secrets: inherit
    with:
      REPO: "alstraab/alstra-web"

  survey-generator:
    needs: check-first-monday
    if: needs.check-first-monday.outputs.is_first_monday == 'true'
    uses: ./.github/workflows/template-scheduled-reminder.yml
    secrets: inherit
    with:
      REPO: "alstraab/survey-generator"

  wtw-blue:
    needs: check-first-monday
    if: needs.check-first-monday.outputs.is_first_monday == 'true'
    uses: ./.github/workflows/template-scheduled-reminder.yml
    secrets: inherit
    with:
      REPO: "alstraab/wtw-blue"
